name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Build, Test & Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test Tests/Kodify.Tests.csproj --configuration Release --logger "trx;LogFileName=TestResults.trx"

    - name: Publish test results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: "TestResults/**/*.trx"
        reporter: dotnet-trx

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kodify-build
        path: |
          **/bin/Release/net8.0/*
          **/publish/ 